# NOTE: update this with your service name
service: fsa-sls

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  create:
    handler: users.create
    events:
      - http:
          path: users
          method: post
          cors: true
  getOne:
    handler: users.getOne
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
  getAll:
    handler: users.getAll
    events:
     - http:
         path: users
         method: get
         cors: true
  update:
    handler: users.update
    events:
     - http:
         path: users/{id}
         method: put
         cors: true
  delete:
    handler: users.delete
    events:
     - http:
         path: users/{id}
         method: delete
         cors: true
  createExperience:
    handler: experience.createExperience
    events:
      - http:
          path: experience
          method: post
          cors: true
  getOneExperience:
    handler: experience.getOneExperience
    events:
      - http:
          path: experience/{id}
          method: get
          cors: true
  getAllExperiences:
    handler: experience.getAllExperiences
    events:
     - http:
         path: experience
         method: get
         cors: true
  updateExperience:
    handler: experience.updateExperience
    events:
     - http:
         path: experience/{id}
         method: put
         cors: true
  deleteExperience:
    handler: experience.delete
    events:
     - http:
         path: experience/{id}
         method: delete
         cors: true